import torch
import numpy as np
my_tensor=torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device=device,requires_grad=True)
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)
q=torch.empty(size=(3,3))
w=torch.zeros((3,3))
e=torch.rand((3,3))
r=torch.ones((3,3))
t=torch.eye(5,5)
u=torch.arange(start=0,end=5,step=1)
i=torch.linspace(start=0.1,end=1,steps=10)
a=torch.empty(size=(1,3)).normal_(mean=0,std=1)
s=torch.empty(size=(1,5)).uniform_(0,1)
d=torch.diag(torch.ones(3))
tensor=torch.arange(4)
print(tensor.bool())
print(tensor.short())
print(tensor.long())
print(tensor.half())
print(tensor.float())
print(tensor.double())
np_array=np.zeros((5,5))
tensor2=torch.from_numpy(np_array)
np_array_back=tensor2.numpy()
